### ISSUE TITLE
ldns_rr_new rr.c:27: Direct leak of 48 byte(s) in 1 object(s)

### ISSUE THREAD

**Issue by noloader** [NLnetLabs/ldns#84]
Asan testing is producing some findings in `12-unit-tests-dnssec.c`. Also see [Travis test results](https://travis-ci.com/NLnetLabs/ldns/jobs/293788254).

```
==5141==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7f913b6fbb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7f913b3cce4a in ldns_rr_new rr.c:27

Indirect leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7f913b6fbb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7f913b3c5b4d in ldns_rdf_new_frm_data rdata.c:203

Indirect leak of 20 byte(s) in 2 object(s) allocated from:
    #0 0x7f913b6fbb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7f913b3c5b61 in ldns_rdf_new_frm_data rdata.c:207

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f913b6fbb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7f913b3cd015 in ldns_rr_push_rdf rr.c:860

SUMMARY: AddressSanitizer: 124 byte(s) leaked in 6 allocation(s).
```

**Comment by noloader** [comment]
Cleared in [Commit 0da3c6ff73fa](https://github.com/NLnetLabs/ldns/commit/0da3c6ff73fa).
