### ISSUE TITLE
13-unit-tests-base.c:250: Direct leak of 195 byte(s) in 11 object(s)

### ISSUE THREAD

**Issue by noloader** [NLnetLabs/ldns#86]
Asan testing is producing some findings in `13-unit-tests-base.c`. Also see [Travis test results](https://travis-ci.com/noloader/ldns/jobs/295114731).

```
==5323==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 195 byte(s) in 11 object(s) allocated from:
    #0 0x7f0df9b5db50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x55f7923b25a2 in test_base32_decode_extended_hex 13-unit-tests-base.c:250

Direct leak of 135 byte(s) in 9 object(s) allocated from:
    #0 0x7f0df9b5db50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x55f7923b2052 in test_base32_decode 13-unit-tests-base.c:158

Direct leak of 55 byte(s) in 10 object(s) allocated from:
    #0 0x7f0df9b5db50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x55f7923b1ab0 in test_base64_decode 13-unit-tests-base.c:68

SUMMARY: AddressSanitizer: 385 byte(s) leaked in 30 allocation(s).
```

**Comment by noloader** [comment]
Cleared in [Commit 44f6700bb619](https://github.com/NLnetLabs/ldns/commit/44f6700bb619).
